### ISSUE TITLE
Identity cookie "twitter_anywhere_identity" was not sent.

### ISSUE THREAD

**Issue by leabaertschi** [FriendsOfSymfony/FOSTwitterBundle#10]
It seems twitter is not sending the 'twitter_anywhere_identity" cookie anymore. When looking at the response headers of the https://oauth.twitter.com/2/authorize request I only get the _twitter_sess cookie back.

Response headers:

Cache-Control:no-cache, no-store, must-revalidate, pre-check=0, post-check=0
Connection:Keep-Alive
Content-Encoding:gzip
Content-Length:268
Content-Type:text/html; charset=utf-8
Date:Tue, 30 Aug 2011 08:22:51 GMT
Expires:Tue, 31 Mar 1981 05:00:00 GMT
Keep-Alive:timeout=15, max=99
Last-Modified:Tue, 30 Aug 2011 08:22:51 GMT
Location: CALLBACKURL#oauth_access_token=cjwGAQAAAADbnVxOAAAAAAxoEgAAAAAAeUcHBPSKJqOry9iBnlpDnyJF1T0=kbMnz9NbcgZ6kAaRjHfRZQmCYfsXLyBJJS06JNZI2&oauth_bridge_code=UoO8wJj6d28TtPtweENVWCiJssmwbewDnrTUD2Sic
Pragma:no-cache
Server:hi
Set-Cookie:lang=en; path=/, lang=en; path=/, _twitter_sess=BAh7DToOcmV0dXJuX3RvIgJQAWh0dHBzOi8vb2F1dGgudHdpdHRlci5jb20v%250AMi9hdXRob3JpemU%252Fb2F1dGhfY2FsbGJhY2tfdXJsPWh0dHAlM0ElMkYlMkZy%250Ab2NrZXRsYWIubG8lMkZyb2NrZXRsYWJfZGV2LnBocCUyRnR3aXR0ZXJfY2hl%250AY2smb2F1dGhfbW9kZT1mbG93X3dlYl9jbGllbnQmb2F1dGhfY2xpZW50X2lk%250AZW50aWZpZXI9eG9OdmhqdjdiT1IwTFZEUHNVY3BxUSZyZWRpcmVjdF91cmk9%250AaHR0cCUzQSUyRiUyRnJvY2tldGxhYi5sbyUyRnJvY2tldGxhYl9kZXYucGhw%250AJTJGdHdpdHRlcl9jaGVjayZyZXNwb25zZV90eXBlPXRva2VuJl89MTMxNDY5%250AMjU2NTY3NiZjbGllbnRfaWQ9eG9OdmhqdjdiT1IwTFZEUHNVY3BxUToPY3Jl%250AYXRlZF9hdGwrCFYkixkyAToMY3NyZl9pZCIlNWVhZGFkMmIzMTdkOTg0ZWQz%250ANTU2ZDE4YWQyYTU0MjI6CXVzZXJpBHI8BgE6B3VhInhNb3ppbGxhLzUuMCAo%250ATWFjaW50b3NoOyBJbnRlbCBNYWMgT1MgWCAxMF83XzEpIEFwcGxlV2ViS2l0%250ALzUzNC40OC4zIChLSFRNTCwgbGlrZSBHZWNrbykgVmVyc2lvbi81LjEgU2Fm%250AYXJpLzUzNC40OC4zOhNwYXNzd29yZF90b2tlbiItYjAxZjhhZDE2YWZmZjli%250ANzNkYzNmZWE5NWM5YTRlMmZkOTIzN2I2NiIKZmxhc2hJQzonQWN0aW9uQ29u%250AdHJvbGxlcjo6Rmxhc2g6OkZsYXNoSGFzaHsABjoKQHVzZWR7ADoHaWQiJTI5%250AYzM4ZGI4ODBiMDE1ZjFkNGY3Njg0ZWNiMGU4ZTJi--e662c4949403c38e971dad104e2947d45060ef9c; domain=.twitter.com; path=/; HttpOnly
Status:302 Found
Vary:Accept-Encoding
X-Content-Type-Options:nosniff
X-Frame-Options:DENY
X-MID:f6747a2d81060ac13a7e523fe9e67cae64536a49
X-Revision:DEV
X-Runtime:0.07750
X-Transaction:1314692571-17681-58681
X-XSS-Protection:1; mode=block

Did the twitter api change or did I do something wrong?

**Comment by ivoaz** [comment]
Same for me, any solutions?

**Comment by stof** [comment]
@schmittjoh ping for this as you are the one that implemented it

**Comment by schmittjoh** [comment]
I guess this is just a confusion of server-side vs. the client-side.

**Comment by stof** [comment]
looking at the twitter doc, I think you confused the OAuth login and `@Anywhere`. `'twitter_anywhere_identity` is set by `@Anywhere`, not by the oauth system.
