### ISSUE TITLE
Invalid / expired Token

### ISSUE THREAD

**Issue by gregoryb** [FriendsOfSymfony/FOSTwitterBundle#20]
Hello,

When the user is redirected to the website, i got an "AuthenticationException: Unknown error". The error is located in : FOS\TwitterBundle\Services\Twitter.php

In getAccessToken() , $accessToken is not checked. And it's occures that $accessToken returns "Invalid / expired Token".
$session->set('access_token', $accessToken['oauth_token'])

I don't know why...

**Comment by hhamon** [comment]
Do you use the Twitter Anywhere button?

**Comment by gregoryb** [comment]
Nop. Just à link to connectTwitter route.

**Comment by arghav** [comment]
Probably you have a wrong API key or secret or Twitter was just acting up. It happens at times. Do you still get the error?
