### ISSUE TITLE
Pivate properties and no getter in Twitter class

### ISSUE THREAD

**Issue by hhamon** [FriendsOfSymfony/FOSTwitterBundle#22]
Hi,

Is there any good reasons to have only private properties in the Twitter service class?

I would like to extend it to make my own Twitter service class and have access to the oAuth object. But as it's private... it's dead!

**Comment by arghav** [comment]
You can inject the Twitter API `fos_twitter.api` to your new service. I'm not sure why you want to extend the Twitter service class. The only purpose of it is to authenticate the user.
