### ISSUE TITLE
Twig Extension : Bad overrided function

### ISSUE THREAD

**Issue by sescandell** [FriendsOfSymfony/FOSTwitterBundle#28]
Switching to Twig 1.8.0, I got the following error :

> Twig_Error_Runtime: An exception has been thrown during the compilation of a template ("Catchable Fatal 
> Error: Argument 2 passed to Twig_Environment::addFunction() must implement interface 
> Twig_FunctionInterface, instance of Twig_Filter_Method given, called in /data/projets/project/source/trunk
> /vendor/twig/lib/Twig/Environment.php on line 962 and defined in /data/projets/project/source/trunk/vendor
> /twig/lib/Twig/Environment.php line 895") in "ProjectCoreBundle::layout.html.twig".

Exploring the code, I see in TwitterAnywhereExtension class you override the function "getFunctions()" in order to return an array of Twig_Filter_Method objects. I think the right function to override is "getFilters()" instead.

**Comment by stof** [comment]
no. They should indeed be functions. The appropriate fix is to change them to sue `Twig_Function_Method` instead of `Twig_Filter_Method`. Could you send a PR to the v1.0 branch with a fix ?

**Comment by sescandell** [comment]
Ok. I was wondering if it was the bad function name or the bad objects.

I will find some times to make the PR.

**Comment by omissis** [comment]
it seems I have the same issue, too.

**Comment by sescandell** [comment]
Sorry for the delay,

PR sent
