### ISSUE TITLE
InvalidArgumentException: There is no extension able to load the configuration for "my.twitter.user"

### ISSUE THREAD

**Issue by JeffPalmier** [FriendsOfSymfony/FOSTwitterBundle#41]
Hi, sorry for the title but i thought it was the best way to explain my issue.

I've followed all your readme and installation guide, but i got an issue with the namespace my.twitter.user on the config.yml. It seems like it can be recognized, but it's defined as provider in the security.yml.

Everything works well before i did the last part. So I think it's goodin the appKernel and I already use the FOSUserBundle.

Do you know why do I got that kind of issue ?

Thanks a lot

**Comment by stof** [comment]
can you paste your config.yml ?

**Comment by stof** [comment]
hmm, actually, the readme was showing the definition of the service but omitting to show the top-level `services` key. As this is likely to be confusing for people not knowing the DI component well, I fixed it in 9cdd7e8079b50d

**Comment by JeffPalmier** [comment]
Thanks a lot, the issue was caused about that.

Thanks for your reactivity !!
