### ISSUE TITLE
Twitter @Anywhere does not work with provided TwitterProvider / twitteroauth lib

### ISSUE THREAD

**Issue by theinterned** [FriendsOfSymfony/FOSTwitterBundle#7]
Hello,

As far as I can tell, the Twitter::getAccessToken() method looks for an access token in a request param called 'oauth_token'. Twitter @Anywhere does not set this param, rather it sets a cookie, "twitter_anywhere_identity", from which a user id can be extracted.

If this is the case, it is perhaps misleading to provide instructions on implementing @Anywhere without noting that @anywhere does not work with the security system.

**Comment by schmittjoh** [comment]
The @Anywhere auth has a separate token.

**Comment by theinterned** [comment]
I don't even know what that means?

When I redirect the user to the check path after they login with @Anywhere, I get this:

Notice: Undefined index: oauth_token in /Users/nschwartz/Sites/lg/getconnected/vendor/bundles/FOS/TwitterBundle/Services/Twitter.php line 77

**Comment by schmittjoh** [comment]
Do you have use_twitter_anywhere: true in your firewall configuration?

**Comment by theinterned** [comment]
The above is if I comment-out the error handling in TwitterProvider::authenticate

**Comment by stof** [comment]
@theinterned paste your security config please.

**Comment by theinterned** [comment]
Ha! 

@schmittjoh - thanks - I was not aware of that config param (is it documented anywhere?)

**Comment by schmittjoh** [comment]
see https://gist.github.com/1021384, would be nice if someone could
incorporate that into the docs.

**Comment by theinterned** [comment]
It works now btw

**Comment by theinterned** [comment]
I would be happy to write that up - not sure where the two Ajax handler classes should go though - it doesn't look like they are part of the bundle?

**Comment by schmittjoh** [comment]
No, they are just examples of how they could look like since you probably
don't want to use the framework's default.

**Comment by theinterned** [comment]
@schmittjoh - okay so I am guessing I need to configure these as services in my config.yml? Could you give me a hand on how I would do that?

**Comment by theinterned** [comment]
Also; if you had nay tips on implementing the TwitterUserProvider, that would be much appreciated!

**Comment by ThomasLomas** [comment]
I'd love for some assistance on how this could be done. Willing to pay for someone to write a simple documentation how to implement a Twitter based login.

Thank you

**Comment by theinterned** [comment]
I've got this working now! I'm not suer when I will have time to write it up, but I'd love to do it.

**Comment by ThomasLomas** [comment]
I'd love for you to comment, or even just post samples of code what allowed you to get it going. Would mean a lot.

Thanks a lot :)
